export default {
  "contractCode":"",
  "bondCode":"",
  "customerName":"",
  "customerId":"",
  "customerIdDate":"",
  "customerIdPlace":"",
  "maturityDate":"",
  "roomBalance": 0,
  "couponPayment": 0,
  "buyDate":"",
  "termRate": 0,
  "reinvestmentRate": 0,
  "buyVol": 0,
  "buyVolMin": 0,
  "buyPrice": 0,
  "buyFee": 0,
  "buyValue": 0,
  "numInvestDate": 0,
  "sumCashNoninvest": 0,
  "sumCashInvest": 0,
  "termNoninvest": 0,
  "termInvest": 0,
  "status":""
}
