export default {
  "bondCode": "",
  "bondName": "",
  "roomBalance": 0,
  "maturityDate": "",
  "releaseDate": "",
  "interestFixRate": 0,
  "termFixCount": 0,
  "termRate": 0,
  "issuerBond": "",
  "collateral": "",
  "parValue": 0,
  "issuePrice": 0,
  "issueBondVal": 0,
  "couponPayment": 0,
  "releaseForm": "",
  "termBond": "",
  "depositAgents": "",
  "paymentAgents": "",
  "rightBuyDesc": "",
  "interestFloatRange": ""
}
