export default {
  "contractCode": "",
  "bondCode": "",
  "customerName": "",
  "customerId": "",
  "customerIdDate": "",
  "customerIdPlace": "",
  "buyDate": "",
  "buyVol": 0,
  "buyPrice": 0,
  "buyFee": 0,
  "buyValue": 0,
  "sellContractCode": "",
  "sellDate": "",
  "termRate": 0,
  "sellVol": 0,
  "sellPrice": 0,
  "sellValue": 0,
  "taxPit": 0,
  "taxValue": 0,
  "status": "",
  "accountBankCode": "",
  "bankName": ""
}
