export default {
  '-1000': 'Hệ thống đang bị khóa.',
  '-1001': 'Không tìm thấy thông tin Trái phiếu',
  '-1002': 'Không tìm thấy Lãi suất theo kỳ hạn',
  '-1003': 'Không tính được giá MUA trái phiếu',
  '-1004': 'Không tìm thấy thông tin Khách hàng',
  '-1005': 'Trái phiếu chưa được DUYỆT hoặc ĐÃ_ĐÓNG',
  '-1006': 'Không tìm thấy hợp đồng MUA',
  '-1007': 'Không được phép xóa hợp đồng MUA. Chỉ được phép xóa khi ĐẶT_CHỖ',
  '-1008': 'Không duyệt được hợp đồng MUA.',
  '-1009': 'Chỉ được duyệt hợp đồng khi ngày giao dịch = ngày duyệt',
  '-1010': 'Không tìm thấy thông tin liên kết tài khoản',
  '-1011': 'Không tìm thấy hợp đồng BÁN',
  '-1012': 'Không được phép xóa hợp đồng BÁN. Chỉ được phép xóa khi đang CHỜ',
  '-1013': 'Tài khoản không đủ số dư',
  '-1014': 'Mã Khách hàng không được để trống',
  '-1015': 'Mã trái phiếu không được để trống',
  '-1016': 'Mã kỳ hạn không được để trống',
  '-1017': 'Lãi suất cho vay phải > 0',
  '-1018': 'Trái phiếu không tồn tại hoặc CHƯA DUYỆT',
  '-1019': 'Số dư trái phiếu không được <0',
  '-1020': 'Không tìm thấy mã TRANSACTION',
  '-1021': 'Phải có ngày giao dịch hợp đồng',
  '-1022': 'Ngày giao dịch hợp đồng không nhỏ hơn ngày hiện tại',
  '-1023': 'Không được lập hợp đồng ngày quá khứ',
  '-1024': 'Ngày BÁN không được nhỏ hơn ngày lập hợp đồng',
  '-1025': 'Ngày BÁN không lớn hơn ngày hết hạn trái phiếu',
  '-1026': 'Ngày BÁN trái phiếu phải <= ngày nhận coupon kỳ cuối',
  '-1027': 'Ngày BÁN trái phiếu phải < ngày nhận coupon kỳ cuối',
  '-1028': 'Yêu cầu bắt buộc tick box nếu có ngày hoàn thiện hồ sơ',
  '-1029': 'Không tìm thấy thông tin Khách hàng MUA',
  '-1030': 'Không tìm thấy thông tin khách hàng BÁN',
  '-1031': 'Ngày mở hợp đồng MUA không được để trống',
  '-1032': 'Ngày mở hợp đồng BÁN không được để trống',
  '-1033': 'Ngày đáo hạn hợp đồng MUA không được để trống',
  '-1034': 'Mã hợp đồng BÁN đã tồn tại. Hãy thử lại lần sau.',
  '-1035': 'Mã hợp đồng MUA đã tồn tại. Hãy thử lại lần sau.',
  '-1036': 'Số lượng trái phiếu BÁN phải > 0',
  '-1037': 'Số lượng trái phiếu MUA phải > 0',
  '-1038': 'Số dư BÁN không đủ',
  '-1039': 'Không tìm thấy thông tin hợp đồng BÁN',
  '-1040': 'Không được phép thay đổi thông tin hợp đồng',
  '-1041': 'Chưa khai báo Room kỳ hạn',
  '-1042': 'Không ghi nhận số âm cho room trái chủ',
  '-1043': 'Kênh giao dịch không được để trống',
  '-1044': 'Room kênh trái phiếu chưa được định nghĩa',
  '-1045': 'Không ghi nhận số âm cho room đặt chỗ',
  '-1046': 'Room kỳ hạn đã hết',
  '-1047': 'Không tìm thấy room kỳ hạn',
  '-1048': 'Không ghi nhận số âm khi unblock',
  '-1049': 'Không ghi nhận số âm cho room duyệt mua',
  '-1050': 'Không thể unblock',
  '-1051': 'Chưa khai báo Room khách hàng',
  '-1052': 'Đã hết room trái chủ được phép MUA',
  '-1053': 'Không duyệt được hợp đồng BÁN.',
  '-1054': 'Không xác định được hợp đồng là BÁN BUÔN hay BÁN LẺ',
  '-1055': 'Click đúp',
  '-1056': 'Ngày MUA không được nhỏ hơn ngày lập hợp đồng',
  '-1057': 'Ngày MUA không được thực hiện vào ngày nghỉ/ngày lễ',
  '-1058': 'Số lượng trái phiếu BÁN lại không lớn hơn số lượng trái phiếu MUA',
  '-1059': 'Lãi suất MUA phải >0',
  '-1060': 'Ngày đáo hạn hợp đồng phải lớn hơn ngày giao dịch',
  '-1061': 'Ngày đáo hạn hợp đồng pha',
  '-1062': 'Ngày đáo hạn hợp đồng phải <= ngày nhận coupon kỳ cuối',
  '-1063': 'Ngày đáo hạn hợp đồng  phải < ngày nhận coupon kỳ cuối',
  '-1064': 'Ngày đáo hạn hợp đồng  phải < ngày đáo hạn trái phiếu',
  '-1065': 'Ngày đáo hạn hợp đồng không được để trống',
  '-1066': 'Ngày giao dịch hợp đồng phải nhỏ hơn ngày đáo hạn trái phiếu',
  '-1067': 'Ngày giao dịch hợp đồng phải nhỏ hơn ngày nhận coupon kỳ cuối',
  '-1068': 'Thông tin trái phiếu chưa được duyệt',
  '-1069': 'Ngày mở hợp đồng MUA không được để trống',
  '-1070': 'Ngày đặt chỗ chỉ trước 3 ngày giao dịch',
  '-1071': 'Mã hợp đồng không được để trống',
  '-1072': 'Không được phép hủy hợp đồng',
  '-1073': 'Không tìm thấy hợp đồng kênh phân phối',
  '-1074': 'Không tìm thấy thông tin kỳ hạn',
  '-1075': 'Không tìm thấy biểu lãi suất phù hợp',
  '-1076': 'Xảy ra lỗi khi tính giá BÁN',
  '-1077': 'Giá trị MUA phải > 0',
  '-1078': 'Số lượng MUA phải lớn hơn số lượng tối thiểu theo quy định',
  '-1079': 'Chưa thiết lập room để khách hàng có thể bán trái phiếu',
  '-1080': 'Đã hết room Khách hàng có thể bán. Hãy thử 1 ngày Bán khác.',
  '-1081': 'Không được nhập số âm (<0)',
  '-1082': '',
  '-1083': '',
  '-1084': '',
  '-1085': '',
  '-1086': '',
  '-1087': '',
  '-1088': '',
  '-1089': '',
  '-1090': '',
  '-1091': '',
  '-1092': '',
  '-1093': '',
  '-1094': '',
  '-1095': '',
  '-1096': '',
  '-1097': '',
  '-1098': '',
  '-1099': '',
  '-1100': 'Xác thực OTP chưa chính xác',
  '-1101': 'Chưa thiết lập OTP',
  '-1102': ''
};
